# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch

import torch


# Create random tensor

random_tensor = torch.rand(size=(7,7))
random_tensor


tensor([[0.3797, 0.2177, 0.3318, 0.5851, 0.5541, 0.7398, 0.9544],
        [0.4131, 0.3156, 0.3072, 0.0316, 0.7240, 0.6481, 0.5512],
        [0.0115, 0.6618, 0.7192, 0.5632, 0.2626, 0.2249, 0.9812],
        [0.4320, 0.2416, 0.2796, 0.6424, 0.0214, 0.5456, 0.0895],
        [0.4278, 0.2983, 0.6717, 0.6752, 0.3296, 0.5953, 0.3437],
        [0.5791, 0.5046, 0.6611, 0.2274, 0.4242, 0.6995, 0.8836],
        [0.2364, 0.7553, 0.8330, 0.0578, 0.1464, 0.3263, 0.5083]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor

random_tensor_2 = torch.rand(size=(1,7))

ran_trans = random_tensor_2.T
print(ran_trans)

elementwise_mul = random_tensor * ran_trans


# Perform matrix multiplication 
MATRIX_mul = random_tensor @ ran_trans        # two ways you can do matrix multipication 
MATRIX_mul_2 = torch.matmul(random_tensor, ran_trans)    # using torch.matmul function 
MATRIX_mul_2


tensor([[0.4856],
        [0.7997],
        [0.1021],
        [0.5438],
        [0.9349],
        [0.7787],
        [0.3865]])


tensor([[2.1737],
        [1.8962],
        [1.7144],
        [1.2603],
        [1.7866],
        [2.1587],
        [1.4227]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
import random 

# Set manual seed
RANDOM_SEED = 42



# Create two random tensors

#setting seed 

torch.manual_seed(seed=RANDOM_SEED)


tensor_1 = torch.rand(3,4)

# setting seed again 
torch.manual_seed(seed=RANDOM_SEED)

tensor_2 = torch.rand(4,3)


# Matrix multiply tensors

mat_product = torch.matmul(tensor_1, tensor_2)

mat_product 


tensor([[1.8822, 2.3650, 1.8172],
        [1.0925, 1.5372, 1.2230],
        [1.2766, 2.2093, 1.6718]])

In [12]:
mat_product = torch.matmul(tensor_1, tensor_2)     # same result we will find, since we set the seed 
mat_product          # seed is an awesome way to ensure the reproducibilty 

tensor([[1.8822, 2.3650, 1.8172],
        [1.0925, 1.5372, 1.2230],
        [1.2766, 2.2093, 1.6718]])

In [13]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU

tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor_back_cpu = tensor_on_gpu.cpu()

tensor_back_cpu, tensor_back_cpu.device



tensor([1, 2, 3]) cpu


(tensor([1, 2, 3]), device(type='cpu'))


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed

torch.manual_seed(1234)

"""
    creating two random tensors in gpu 
    settiing manual seed for reproducibility 

    sent both of the tensors into the gpu 
    then performed the matrix multipication into gpu 


"""

tensor1 = torch.rand(3,4)
gpu_tensor1= tensor1.to(device)


tensor2 = torch.rand(3,4)
gpu_tensor2= tensor2.to(device)
gpu_tensor_3 = gpu_tensor2.T

gpu_tensor1, gpu_tensor2

#performing matrix multipication 

mat_mul = torch.matmul(gpu_tensor1, gpu_tensor_3)
mat_mul
print( tensor1)
print(tensor2)
mat_mul

max_value = mat_mul.max()
min_value = mat_mul.min()

arg_max = mat_mul.argmax()
arg_min = mat_mul.argmin()

mean_value = mat_mul.mean()

max_value, min_value, arg_max, arg_min, mean_value



tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])


(tensor(1.3969, device='mps:0'),
 tensor(0.4367, device='mps:0'),
 tensor(6, device='mps:0'),
 tensor(2, device='mps:0'),
 tensor(0.8355, device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B

#done


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions

#this one needs to be done, this is a bit complicated to me 


# Print out tensors and their shapes
